const amenities = [
  { icon: 'parking', filter: 'amenity=parking' },
  { icon: 'cathedral', filter: 'amenity=place_of_worship' },
  { icon: 'school', filter: 'amenity=school' },
  { icon: 'bench', filter: 'amenity=bench' },
  { icon: 'restaurant', filter: 'amenity=restaurant' },
  { icon: 'gas-station', filter: 'amenity=fuel' },
  { icon: 'cafe', filter: 'amenity=cafe' },
  { icon: 'hamburger', filter: 'amenity=fast_food' },
  { icon: 'bank', filter: 'amenity=bank' },
  { icon: 'post-box', filter: 'amenity=post_box' },
  { icon: 'waste', filter: 'amenity=waste_basket' },
  { icon: 'pill', filter: 'amenity=pharmacy' },
  { icon: 'bicycle', filter: 'amenity=bicycle_parking' },
  { icon: 'toilet', filter: 'amenity=toilets' },
  { icon: 'recycling', filter: 'amenity=recycling' },
  { icon: 'children', filter: 'amenity=kindergarten' },
  { icon: 'home', filter: 'amenity=shelter' },
  { icon: 'cemetery', filter: 'amenity=grave_yard' },
  { icon: 'water', filter: 'amenity=drinking_water' },
  { icon: 'post-office', filter: 'amenity=post_office' },
  { icon: 'hospital', filter: 'amenity=hospital' },
  { icon: 'beer', filter: 'amenity=pub' },
  { icon: 'atm', filter: 'amenity=atm' },
  { icon: 'bar', filter: 'amenity=bar' },
  { icon: 'police', filter: 'amenity=police' },
  { icon: 'vending-machine', filter: 'amenity=vending_machine' },
  { icon: 'city-hall', filter: 'amenity=townhall' },
  { icon: 'fire-station', filter: 'amenity=fire_station' },
  { icon: 'book', filter: 'amenity=library' }
]

export default amenities
