const amenities = [
  { name: 'Parkingi', icon: 'parking', filter: 'amenity=parking' },
  { name: 'Świątynie', icon: 'cathedral', filter: 'amenity=place_of_worship' },
  { name: 'Szkoły', icon: 'school', filter: 'amenity=school' },
  { name: 'Ławki', icon: 'bench', filter: 'amenity=bench' },
  { name: 'Restauracje', icon: 'restaurant', filter: 'amenity=restaurant' },
  { name: 'Stacje benzynowe', icon: 'gas-station', filter: 'amenity=fuel' },
  { name: 'Kawiarnie', icon: 'cafe', filter: 'amenity=cafe' },
  { name: 'Fast foody', icon: 'hamburger', filter: 'amenity=fast_food' },
  { name: 'Banki', icon: 'bank', filter: 'amenity=bank' },
  { name: 'Skrzynki pocztowe', icon: 'post-box', filter: 'amenity=post_box' },
  { name: 'Kosze na śmieci', icon: 'waste', filter: 'amenity=waste_basket' },
  { name: 'Apteki', icon: 'pill', filter: 'amenity=pharmacy' },
  { name: 'Parkingi rowerowe', icon: 'bicycle', filter: 'amenity=bicycle_parking' },
  { name: 'Toalety', icon: 'toilet', filter: 'amenity=toilets' },
  { name: 'Recykling', icon: 'recycling', filter: 'amenity=recycling' },
  { name: 'Przedszkola', icon: 'children', filter: 'amenity=kindergarten' },
  { name: 'Schroniska', icon: 'home', filter: 'amenity=shelter' },
  { name: 'Cmentarze', icon: 'cemetery', filter: 'amenity=grave_yard' },
  { name: 'Woda do picia', icon: 'water', filter: 'amenity=drinking_water' },
  { name: 'Poczta', icon: 'post-office', filter: 'amenity=post_office' },
  { name: 'Szpitale', icon: 'hospital', filter: 'amenity=hospital' },
  { name: 'Puby', icon: 'beer', filter: 'amenity=pub' },
  { name: 'Bankomaty', icon: 'atm', filter: 'amenity=atm' },
  { name: 'Bary', icon: 'bar', filter: 'amenity=bar' },
  { name: 'Policja', icon: 'police', filter: 'amenity=police' },
  { name: 'Automaty', icon: 'vending-machine', filter: 'amenity=vending_machine' },
  { name: 'Ratusze', icon: 'city-hall', filter: 'amenity=townhall' },
  { name: 'Straż pożarna', icon: 'fire-station', filter: 'amenity=fire_station' }
]

export default amenities
