version: 2
jobs:
  build:
    working_directory: ~/osm-browser
    docker:
      - image: osmbrowser/ci
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build and test
          command: docker-compose up -d
          environment:
            COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
      - run:
          build: Push image
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then exit 0; fi
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push osmbrowser/$CIRCLE_PROJECT_REPONAME:$CIRCLE_WORKFLOW_WORKSPACE_ID
      - persist_to_workspace:
          root: chart
          paths:
            - '*'
  deploy:
    working_directory: ~/osm-browser
    docker:
      - image: osmbrowser/ci
    steps:
      - attach_workspace:
          at: chart
      - run:
          name: Configure kubectl
          command: |
            echo $K8S_CA | base64 -d > ca.crt
            kubectl config set-cluster default --server=$K8S_URL --certificate-authority=ca.crt
            kubectl config set-credentials default --token=$(echo $K8S_TOKEN | base64 -d)
            kubectl config set-context default --cluster=default --user=default
            kubectl config use-context default
      - run:
          name: Upgrade release
          command: |
            helm init -c
            helm upgrade ${CIRCLE_PROJECT_REPONAME} ./chart \
              --set image.tag=$CIRCLE_WORKFLOW_WORKSPACE_ID \
              --reuse-values --timeout 300 --wait
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
      - deploy:
          context: org-global
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
